[package]
name = "{{project-name | snake_case}}"
version = "0.1.0"
edition = "2021"

[dependencies]
wit-bindgen = "0.16.0"
serde_json = "1.0"

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "component:{{project-name | kebab_case}}"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"

[profile.dev]
opt-level = 1
debug = true

[workspace]