[package]
name = "echo-tool"
version = "0.1.0"
edition = "2021"

[dependencies]
ftl-sdk-rs = { path = "../packages/ftl-sdk-rs" }
spin-sdk = "3.1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
crate-type = ["cdylib"]

[workspace]