[project]
name = "{{project-name | kebab_case}}"
version = "0.1.0"
description = "{{project-description}}"
authors = ["{{authors}}"]

# ========================================
# OAuth Configuration (Optional)
# ========================================
# If no [oauth] section: public access (no authentication)
# If [oauth] section present: custom OAuth authentication

# For custom OAuth (Auth0, Okta, etc.):
# [oauth]
# issuer = "https://your-domain.auth0.com"
# audience = "your-api-identifier"  # optional
# jwks_uri = "https://your-domain.auth0.com/.well-known/jwks.json"
# public_key = ""  # optional - PEM format public key (alternative to JWKS)
# algorithm = "RS256"  # optional - JWT signing algorithm
# required_scopes = "read,write"  # optional
# authorize_endpoint = "https://your-domain.auth0.com/authorize"  # optional - for OAuth discovery
# token_endpoint = "https://your-domain.auth0.com/oauth/token"  # optional - for OAuth discovery
# userinfo_endpoint = "https://your-domain.auth0.com/userinfo"  # optional - for OAuth discovery


[mcp]
# MCP components with full registry URIs
gateway = "ghcr.io/fastertools/mcp-gateway:0.0.12"
authorizer = "ghcr.io/fastertools/mcp-authorizer:0.0.14"
# You can use custom implementations by changing the URIs:
# gateway = "ghcr.io/myorg/custom-mcp-gateway:1.0.0"
# authorizer = "ghcr.io/myorg/custom-mcp-authorizer:1.0.0"
validate_arguments = true

# Add your components here using 'ftl add <component-name>'
# Example:
# [component.echo]
# path = "echo"
# wasm = "echo/target/wasm32-wasip1/release/echo.wasm"
# allowed_outbound_hosts = []
# 
# [component.echo.build]
# command = "cargo build --target wasm32-wasip1 --release"
# watch = ["src/**/*.rs", "Cargo.toml"]