[project]
name = "{{project-name | kebab_case}}"
version = "0.1.0"
description = "{{project-description}}"
authors = ["{{authors}}"]

# ========================================
# Auth Gateway Configuration
# ========================================
# Authentication is DISABLED by default. To enable, set auth_enabled = true

[auth]
enabled = false
provider = ""  # "authkit" or "oidc"
issuer = ""
audience = ""

# OIDC-specific settings (only required for provider = "oidc")
[auth.oidc]
provider_name = ""
jwks_uri = ""
authorize_endpoint = ""
token_endpoint = ""
userinfo_endpoint = ""
allowed_domains = ""  # comma-separated list

# ========================================
# Example configurations:
# ========================================
# AuthKit:
#   [auth]
#   enabled = true
#   provider = "authkit"
#   issuer = "https://your-tenant.authkit.app"
#   audience = "mcp-api"  # optional
#
# Auth0:
#   [auth]
#   enabled = true
#   provider = "oidc"
#   issuer = "https://your-domain.auth0.com"
#   audience = "your-api-identifier"  # optional
#   
#   [auth.oidc]
#   provider_name = "auth0"
#   jwks_uri = "https://your-domain.auth0.com/.well-known/jwks.json"
#   authorize_endpoint = "https://your-domain.auth0.com/authorize"
#   token_endpoint = "https://your-domain.auth0.com/oauth/token"
#   userinfo_endpoint = "https://your-domain.auth0.com/userinfo"  # optional
#   allowed_domains = "*.auth0.com"  # optional

[gateway]
version = "0.0.9"
authorizer_version = "0.0.9"
validate_arguments = true

# Add your tools here using 'ftl add <tool-name>'
# Example:
# [tools.echo]
# path = "echo"
# allowed_outbound_hosts = []
# 
# [tools.echo.build]
# command = "cargo build --target wasm32-wasip1 --release"
# watch = ["src/**/*.rs", "Cargo.toml"]