[project]
name = "{{project-name | kebab_case}}"
version = "0.1.0"
description = "{{project-description}}"
authors = ["{{authors}}"]

# ========================================
# Auth Gateway Configuration
# ========================================
# Authentication is DISABLED by default. To enable, set auth_enabled = true

[auth]
enabled = false

# Uncomment and configure one of the following auth providers when enabling auth:

# For AuthKit:
# [auth.authkit]
# issuer = "https://your-tenant.authkit.app"
# audience = "mcp-api"  # optional
# required_scopes = "mcp:read,mcp:write"  # optional

# For OIDC (Auth0, Okta, etc.):
# [auth.oidc]
# issuer = "https://your-domain.auth0.com"
# audience = "your-api-identifier"  # optional
# jwks_uri = "https://your-domain.auth0.com/.well-known/jwks.json"
# public_key = ""  # optional - PEM format public key (alternative to JWKS)
# algorithm = "RS256"  # optional - JWT signing algorithm
# required_scopes = "read,write"  # optional
# authorize_endpoint = "https://your-domain.auth0.com/authorize"  # optional - for OAuth discovery
# token_endpoint = "https://your-domain.auth0.com/oauth/token"  # optional - for OAuth discovery
# userinfo_endpoint = "https://your-domain.auth0.com/userinfo"  # optional - for OAuth discovery

# For Static Tokens (development only):
# [auth.static_token]
# tokens = "dev-token:client1:user1:read,write"
# required_scopes = "read"  # optional


[mcp]
# MCP components with full registry URIs
gateway = "ghcr.io/fastertools/mcp-gateway:0.0.10"
authorizer = "ghcr.io/fastertools/mcp-authorizer:0.0.10"
# You can use custom implementations by changing the URIs:
# gateway = "ghcr.io/myorg/custom-mcp-gateway:1.0.0"
# authorizer = "ghcr.io/myorg/custom-mcp-authorizer:1.0.0"
validate_arguments = true

# Add your tools here using 'ftl add <tool-name>'
# Example:
# [tools.echo]
# path = "echo"
# wasm = "echo/target/wasm32-wasip1/release/echo.wasm"
# allowed_outbound_hosts = []
# 
# [tools.echo.build]
# command = "cargo build --target wasm32-wasip1 --release"
# watch = ["src/**/*.rs", "Cargo.toml"]