spin_manifest_version = 2

[application]
name = "hello-python"
version = "0.1.0"
description = "A minimal Python FTL tool example"
authors = ["FTL CLI Contributors"]

[[trigger.http]]
route = "/..."
component = "hello-python"

[component.hello-python]
source = "app_ftl.wasm"
[component.hello-python.build]
command = "bash -c 'source venv/bin/activate && componentize-py -w spin-http componentize app_ftl -o app_ftl.wasm'"