# Clippy configuration for strict code quality

# Set MSRV (Minimum Supported Rust Version)
msrv = "1.75.0"

# Cognitive complexity threshold
cognitive-complexity-threshold = 30

# Maximum number of lines for functions
too-many-lines-threshold = 100

# Maximum number of arguments
too-many-arguments-threshold = 7

# Type complexity threshold
type-complexity-threshold = 250

# Disallowed names
disallowed-names = ["foo", "bar", "baz", "quux"]

# Allow certain lints in tests
allow-dbg-in-tests = true
allow-print-in-tests = true
allow-unwrap-in-tests = true
allow-expect-in-tests = true