run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - errcheck
    - gosec
    - gofmt
    - goimports
    - misspell
    - revive
    - unconvert
    - unparam

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  govet:
    check-shadowing: false
  revive:
    ignore-generated-header: true
    severity: warning

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - unparam
    - path: test_
      linters:
        - gosec
        - errcheck
    - path: internal/cli/test_helpers\.go
      linters:
        - unused
  max-issues-per-linter: 0
  max-same-issues: 0