[workspace]
members = ["ftl-cli", "ftl-core"]
exclude = ["demo_hash", "toolkit-*"]
resolver = "2"

# Don't build CLI for wasm target
[workspace.metadata.cargo-all-features]
skip_targets = ["wasm32-wasip1"]

[workspace.package]
version = "0.0.1"
authors = ["FTL Contributors"]
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/ftl-tooling/ftl-cli"
homepage = "https://github.com/ftl-tooling/ftl-cli"
documentation = "https://docs.rs/ftl"
keywords = ["wasm", "mcp", "tools", "cli", "webassembly"]
categories = ["command-line-utilities", "development-tools", "wasm"]

[workspace.dependencies]
clap = { version = "4.5", features = ["derive", "env"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
anyhow = "1.0"
thiserror = "1.0"
tokio = { version = "1.35", features = ["rt", "rt-multi-thread", "macros", "time", "process", "signal", "fs"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tempfile = "3.8"
which = "6.0"
handlebars = "6.0"
walkdir = "2.4"
notify = "6.1"
include_dir = "0.7"

# Optimization profiles
[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"

[profile.tiny]
inherits = "release"
opt-level = "z"

[profile.dev]
opt-level = 1
debug = true