# FTL CLI - Rust Formatting Configuration
# Using stable rustfmt features only

edition = "2024"

# Line width and wrapping
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"

# Imports and modules
reorder_imports = true
reorder_modules = true

# Code simplification
use_field_init_shorthand = true
use_try_shorthand = true
remove_nested_parens = true
merge_derives = true

# Function and method formatting
fn_params_layout = "Tall"

# Match expressions
match_arm_leading_pipes = "Never"
match_block_trailing_comma = false

# Misc
force_explicit_abi = true