spin_manifest_version = 2

[application]
name = "my-ftl-app"
version = "0.1.0"
description = "Test FTL app for tools command"
authors = ["test@example.com"]

[variables]
tool_components = { default = "existing-tool,json-format,http-get,dns-lookup,base64-encode" }

[[trigger.http]]
route = "/..."
component = "mcp-gateway"

[component.mcp-gateway]
source = { registry = "ghcr.io/fastertools/ftl-mcp-gateway:latest" }
variables = { tool_components = "{{ tool_components }}" }

[component.existing-tool]
source = { registry = "ghcr.io/fastertools/ftl-tool-existing:latest" }

[component.json-format]
source = { registry = "ghcr.io/fastertools/ftl-tool-json-format:latest" }

[component.http-get]
source = { registry = "ghcr.io/fastertools/ftl-tool-http-get:latest" }

[component.dns-lookup]
source = { registry = "ghcr.io/fastertools/ftl-tool-dns-lookup:latest" }

[component.base64-encode]
source = { registry = "123456789012.dkr.ecr.us-west-2.amazonaws.com/ftl-tool-base64-encode:latest" }
