name: 'Setup Git for Automation'
description: 'Configure Git for automated commits and PR creation'
inputs:
  token:
    description: 'GitHub token for authentication'
    required: false
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
    - name: Setup Git
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        # Configure git to use the token for authentication
        git config --global url."https://x-access-token:${{ inputs.token }}@github.com/".insteadOf "https://github.com/"