# Example spinc.yaml configuration
# This demonstrates the schema that both CLI and platform understand

application:
  name: my-mcp-app
  version: 1.0.0
  description: Example MCP application
  authors:
    - FTL Team

components:
  # User component (pushed to registry)
  - id: weather-tool
    source: 123456789.dkr.ecr.us-west-2.amazonaws.com/ftl/app-123/weather-tool:v1.0.0
    description: MCP tool for weather data
    allowed_outbound_hosts:
      - "https://api.weather.com"
    environment:
      API_KEY: "{{ secrets.weather_api_key }}"

  # Another user component
  - id: calculator-tool  
    source: 123456789.dkr.ecr.us-west-2.amazonaws.com/ftl/app-123/calculator:v1.0.0
    description: MCP tool for calculations

triggers:
  - type: http
    component: weather-tool
    route: /weather/*
    
  - type: http
    component: calculator-tool
    route: /calc/*

variables:
  log_level: info
  environment: production

mcp:
  gateway:
    enabled: true
    # Platform will inject its MCP gateway component here
    
  authorizer:
    enabled: true
    access_control: private  # Require authentication
    # Platform will configure AuthKit integration