spin_manifest_version = 2

[application]
name = "my-test-app"
version = "0.1.0"

[[component]]
id = "weather-tool"
source = "dummy.wasm"

[component.trigger]
route = "/weather"

[[component]]
id = "calculator"
source = "dummy2.wasm"