application:
    name: my-test-app
    version: 0.1.0
    description: my-test-app - An FTL application
components:
    - id: weather-tool
      source: registry://example.com/weather:v1.0.0
    - id: calculator
      source: ./calculator
      description: Calculator tool for math operations
triggers:
    - type: http
      component: weather-tool
      route: /weather
