#!/bin/bash

echo "Debug: Checking deployment error..."
echo ""
echo "The error shows:"
echo "  URL: https://795394005211.dkr.ecr.us-west-2.amazonaws.com/v2/math/graph/blobs/uploads/"
echo "  Status: 401 Not Authorized"
echo ""
echo "This indicates:"
echo "1. The namespace 'math' is being used (good - it's the sanitized app name)"
echo "2. The repository path is: math/graph"
echo "3. The ECR token authentication is failing"
echo ""
echo "Possible causes:"
echo "a) The ECR repository 'math/graph' doesn't exist yet"
echo "b) The ECR token doesn't have push permissions for this namespace"
echo "c) The backend needs to create repositories before we can push"
echo ""
echo "The backend should be:"
echo "1. Creating ECR repositories when the app is created"
echo "2. OR creating them when we request the ECR token"
echo "3. OR we need to call UpdateComponents first to register them"
