// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for AppAccessControl.
const (
	AppAccessControlCustom  AppAccessControl = "custom"
	AppAccessControlOrg     AppAccessControl = "org"
	AppAccessControlPrivate AppAccessControl = "private"
	AppAccessControlPublic  AppAccessControl = "public"
)

// Defines values for AppLatestDeploymentStatus.
const (
	AppLatestDeploymentStatusDeployed   AppLatestDeploymentStatus = "deployed"
	AppLatestDeploymentStatusDeploying  AppLatestDeploymentStatus = "deploying"
	AppLatestDeploymentStatusFailed     AppLatestDeploymentStatus = "failed"
	AppLatestDeploymentStatusPending    AppLatestDeploymentStatus = "pending"
	AppLatestDeploymentStatusRolledBack AppLatestDeploymentStatus = "rolled_back"
)

// Defines values for AppStatus.
const (
	AppStatusACTIVE   AppStatus = "ACTIVE"
	AppStatusCREATING AppStatus = "CREATING"
	AppStatusDELETED  AppStatus = "DELETED"
	AppStatusDELETING AppStatus = "DELETING"
	AppStatusFAILED   AppStatus = "FAILED"
	AppStatusPENDING  AppStatus = "PENDING"
)

// Defines values for CreateAppRequestAccessControl.
const (
	CreateAppRequestAccessControlCustom  CreateAppRequestAccessControl = "custom"
	CreateAppRequestAccessControlOrg     CreateAppRequestAccessControl = "org"
	CreateAppRequestAccessControlPrivate CreateAppRequestAccessControl = "private"
	CreateAppRequestAccessControlPublic  CreateAppRequestAccessControl = "public"
)

// Defines values for CreateAppResponseBodyStatus.
const (
	CreateAppResponseBodyStatusACTIVE   CreateAppResponseBodyStatus = "ACTIVE"
	CreateAppResponseBodyStatusCREATING CreateAppResponseBodyStatus = "CREATING"
	CreateAppResponseBodyStatusDELETED  CreateAppResponseBodyStatus = "DELETED"
	CreateAppResponseBodyStatusDELETING CreateAppResponseBodyStatus = "DELETING"
	CreateAppResponseBodyStatusFAILED   CreateAppResponseBodyStatus = "FAILED"
	CreateAppResponseBodyStatusPENDING  CreateAppResponseBodyStatus = "PENDING"
)

// Defines values for ListAppsResponseBodyAppsAccessControl.
const (
	Custom  ListAppsResponseBodyAppsAccessControl = "custom"
	Org     ListAppsResponseBodyAppsAccessControl = "org"
	Private ListAppsResponseBodyAppsAccessControl = "private"
	Public  ListAppsResponseBodyAppsAccessControl = "public"
)

// Defines values for ListAppsResponseBodyAppsLatestDeploymentStatus.
const (
	ListAppsResponseBodyAppsLatestDeploymentStatusDeployed   ListAppsResponseBodyAppsLatestDeploymentStatus = "deployed"
	ListAppsResponseBodyAppsLatestDeploymentStatusDeploying  ListAppsResponseBodyAppsLatestDeploymentStatus = "deploying"
	ListAppsResponseBodyAppsLatestDeploymentStatusFailed     ListAppsResponseBodyAppsLatestDeploymentStatus = "failed"
	ListAppsResponseBodyAppsLatestDeploymentStatusPending    ListAppsResponseBodyAppsLatestDeploymentStatus = "pending"
	ListAppsResponseBodyAppsLatestDeploymentStatusRolledBack ListAppsResponseBodyAppsLatestDeploymentStatus = "rolled_back"
)

// Defines values for ListAppsResponseBodyAppsStatus.
const (
	ACTIVE   ListAppsResponseBodyAppsStatus = "ACTIVE"
	CREATING ListAppsResponseBodyAppsStatus = "CREATING"
	DELETED  ListAppsResponseBodyAppsStatus = "DELETED"
	DELETING ListAppsResponseBodyAppsStatus = "DELETING"
	FAILED   ListAppsResponseBodyAppsStatus = "FAILED"
	PENDING  ListAppsResponseBodyAppsStatus = "PENDING"
)

// Defines values for ListAppsParamsIncludeDeleted.
const (
	False ListAppsParamsIncludeDeleted = "false"
	True  ListAppsParamsIncludeDeleted = "true"
)

// App Application object
type App struct {
	AccessControl *AppAccessControl  `json:"accessControl,omitempty"`
	AllowedRoles  *[]string          `json:"allowedRoles,omitempty"`
	AppId         openapi_types.UUID `json:"appId"`
	AppName       string             `json:"appName"`
	CreatedAt     string             `json:"createdAt"`
	CustomAuth    *struct {
		Audience string `json:"audience"`
		Issuer   string `json:"issuer"`
	} `json:"customAuth,omitempty"`

	// LatestDeployment Latest deployment information for this app
	LatestDeployment *struct {
		CreatedAt          *float32                  `json:"createdAt,omitempty"`
		DeployedAt         *float32                  `json:"deployedAt,omitempty"`
		DeploymentDuration *float32                  `json:"deploymentDuration,omitempty"`
		DeploymentId       string                    `json:"deploymentId"`
		Environment        *string                   `json:"environment,omitempty"`
		Status             AppLatestDeploymentStatus `json:"status"`
		StatusMessage      *string                   `json:"statusMessage,omitempty"`
	} `json:"latestDeployment"`
	OrgId         *string   `json:"orgId,omitempty"`
	ProviderError *string   `json:"providerError,omitempty"`
	ProviderUrl   *string   `json:"providerUrl,omitempty"`
	Status        AppStatus `json:"status"`
	UpdatedAt     string    `json:"updatedAt"`
}

// AppAccessControl defines model for App.AccessControl.
type AppAccessControl string

// AppLatestDeploymentStatus defines model for App.LatestDeployment.Status.
type AppLatestDeploymentStatus string

// AppStatus defines model for App.Status.
type AppStatus string

// CreateAppRequest Request body for creating an app
type CreateAppRequest struct {
	// AccessControl Access control mode for the application
	AccessControl *CreateAppRequestAccessControl `json:"accessControl,omitempty"`

	// AppName The name of the application
	AppName string `json:"appName"`
}

// CreateAppRequestAccessControl Access control mode for the application
type CreateAppRequestAccessControl string

// CreateAppResponseBody Response for successful app creation
type CreateAppResponseBody struct {
	AppId     openapi_types.UUID          `json:"appId"`
	AppName   string                      `json:"appName"`
	CreatedAt string                      `json:"createdAt"`
	Status    CreateAppResponseBodyStatus `json:"status"`
	UpdatedAt string                      `json:"updatedAt"`
}

// CreateAppResponseBodyStatus defines model for CreateAppResponseBody.Status.
type CreateAppResponseBodyStatus string

// CreateDeployCredentialsRequest Request body for creating deployment credentials
type CreateDeployCredentialsRequest struct {
	// AppId Application ID to create deployment credentials for
	AppId openapi_types.UUID `json:"appId"`

	// Components Component names to create/ensure repositories for
	Components *[]string `json:"components,omitempty"`
}

// CreateDeployCredentialsResponse Deployment credentials response with registry and deployment access
type CreateDeployCredentialsResponse struct {
	// AppId Application ID
	AppId      openapi_types.UUID `json:"appId"`
	Deployment struct {
		Credentials struct {
			// AccessKeyId AWS access key ID
			AccessKeyId string `json:"accessKeyId"`

			// ExpiresAt Credentials expiration time
			ExpiresAt string `json:"expiresAt"`

			// SecretAccessKey AWS secret access key
			SecretAccessKey string `json:"secretAccessKey"`

			// SessionToken AWS session token
			SessionToken string `json:"sessionToken"`
		} `json:"credentials"`

		// FunctionUrl Lambda function URL for deployment
		FunctionUrl string `json:"functionUrl"`
	} `json:"deployment"`
	Registry struct {
		// AuthorizationToken ECR authorization token
		AuthorizationToken string `json:"authorizationToken"`

		// ExpiresAt ECR token expiration time
		ExpiresAt string `json:"expiresAt"`

		// PackageNamespace ECR namespace for components
		PackageNamespace string `json:"packageNamespace"`

		// ProxyEndpoint ECR proxy endpoint
		ProxyEndpoint string `json:"proxyEndpoint"`

		// Region AWS region
		Region string `json:"region"`

		// RegistryUri ECR registry URI
		RegistryUri string `json:"registryUri"`
	} `json:"registry"`
}

// DeleteAppResponseBody Response for successful app deletion
type DeleteAppResponseBody struct {
	Message string `json:"message"`
}

// ErrorResponse Standard error response format
type ErrorResponse struct {
	Details *[]interface{} `json:"details,omitempty"`
	Error   *string        `json:"error,omitempty"`
	Message string         `json:"message"`
}

// GetAppLogsResponseBody Application logs response
type GetAppLogsResponseBody struct {
	// AppId Application ID
	AppId openapi_types.UUID `json:"appId"`

	// Logs Raw log output from the application
	Logs     string `json:"logs"`
	Metadata struct {
		// Since Time range used for the query
		Since string `json:"since"`

		// Tail Number of lines requested
		Tail float32 `json:"tail"`
	} `json:"metadata"`
}

// GetUserOrgsResponseBody List of user organizations
type GetUserOrgsResponseBody struct {
	// Organizations List of organizations the user belongs to
	Organizations []struct {
		// Id Organization ID from WorkOS
		Id string `json:"id"`

		// Name Organization name
		Name string `json:"name"`
	} `json:"organizations"`
}

// ListAppsResponseBody List of applications
type ListAppsResponseBody struct {
	Apps []struct {
		AccessControl *ListAppsResponseBodyAppsAccessControl `json:"accessControl,omitempty"`
		AllowedRoles  *[]string                              `json:"allowedRoles,omitempty"`
		AppId         openapi_types.UUID                     `json:"appId"`
		AppName       string                                 `json:"appName"`
		CreatedAt     string                                 `json:"createdAt"`
		CustomAuth    *struct {
			Audience string `json:"audience"`
			Issuer   string `json:"issuer"`
		} `json:"customAuth,omitempty"`

		// LatestDeployment Latest deployment information for this app
		LatestDeployment *struct {
			CreatedAt          *float32                                       `json:"createdAt,omitempty"`
			DeployedAt         *float32                                       `json:"deployedAt,omitempty"`
			DeploymentDuration *float32                                       `json:"deploymentDuration,omitempty"`
			DeploymentId       string                                         `json:"deploymentId"`
			Environment        *string                                        `json:"environment,omitempty"`
			Status             ListAppsResponseBodyAppsLatestDeploymentStatus `json:"status"`
			StatusMessage      *string                                        `json:"statusMessage,omitempty"`
		} `json:"latestDeployment"`
		OrgId         *string                        `json:"orgId,omitempty"`
		ProviderError *string                        `json:"providerError,omitempty"`
		ProviderUrl   *string                        `json:"providerUrl,omitempty"`
		Status        ListAppsResponseBodyAppsStatus `json:"status"`
		UpdatedAt     string                         `json:"updatedAt"`
	} `json:"apps"`
}

// ListAppsResponseBodyAppsAccessControl defines model for ListAppsResponseBody.Apps.AccessControl.
type ListAppsResponseBodyAppsAccessControl string

// ListAppsResponseBodyAppsLatestDeploymentStatus defines model for ListAppsResponseBody.Apps.LatestDeployment.Status.
type ListAppsResponseBodyAppsLatestDeploymentStatus string

// ListAppsResponseBodyAppsStatus defines model for ListAppsResponseBody.Apps.Status.
type ListAppsResponseBodyAppsStatus string

// ListComponentsResponseBody List of components for an app
type ListComponentsResponseBody struct {
	AppId      openapi_types.UUID `json:"appId"`
	AppName    string             `json:"appName"`
	Components []struct {
		ComponentName  string  `json:"componentName"`
		Description    *string `json:"description,omitempty"`
		RepositoryName *string `json:"repositoryName,omitempty"`
		RepositoryUri  *string `json:"repositoryUri,omitempty"`
	} `json:"components"`
}

// UpdateComponentsRequest Request body for updating components
type UpdateComponentsRequest struct {
	Components []struct {
		ComponentName string  `json:"componentName"`
		Description   *string `json:"description,omitempty"`
	} `json:"components"`
}

// UpdateComponentsResponseBody Response for successful components update
type UpdateComponentsResponseBody struct {
	Changes struct {
		Created []string `json:"created"`
		Removed []string `json:"removed"`
		Updated []string `json:"updated"`
	} `json:"changes"`
	Components []struct {
		ComponentName  string  `json:"componentName"`
		Description    *string `json:"description,omitempty"`
		RepositoryName *string `json:"repositoryName,omitempty"`
		RepositoryUri  *string `json:"repositoryUri,omitempty"`
	} `json:"components"`
}

// ListAppsParams defines parameters for ListApps.
type ListAppsParams struct {
	// Name Filter by app name (partial match)
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// IncludeDeleted Include deleted apps in the response
	IncludeDeleted *ListAppsParamsIncludeDeleted `form:"includeDeleted,omitempty" json:"includeDeleted,omitempty"`

	// Authorization Bearer token for authentication
	Authorization string `json:"Authorization"`
}

// ListAppsParamsIncludeDeleted defines parameters for ListApps.
type ListAppsParamsIncludeDeleted string

// CreateAppParams defines parameters for CreateApp.
type CreateAppParams struct {
	// Authorization Bearer token for authentication
	Authorization string `json:"Authorization"`
}

// DeleteAppParams defines parameters for DeleteApp.
type DeleteAppParams struct {
	// Authorization Bearer token for authentication
	Authorization string `json:"Authorization"`
}

// GetAppParams defines parameters for GetApp.
type GetAppParams struct {
	// Authorization Bearer token for authentication
	Authorization string `json:"Authorization"`
}

// ListAppComponentsParams defines parameters for ListAppComponents.
type ListAppComponentsParams struct {
	// Authorization Bearer token for authentication
	Authorization string `json:"Authorization"`
}

// UpdateComponentsParams defines parameters for UpdateComponents.
type UpdateComponentsParams struct {
	// Authorization Bearer token for authentication
	Authorization string `json:"Authorization"`
}

// CreateDeployCredentialsParams defines parameters for CreateDeployCredentials.
type CreateDeployCredentialsParams struct {
	// Authorization Bearer token for authentication
	Authorization string `json:"Authorization"`
}

// GetAppLogsParams defines parameters for GetAppLogs.
type GetAppLogsParams struct {
	// Since Time range for logs (e.g., "30m", "1h", "7d", or RFC3339/Unix timestamp)
	Since *string `form:"since,omitempty" json:"since,omitempty"`

	// Tail Number of log lines from the end (1-1000)
	Tail *string `form:"tail,omitempty" json:"tail,omitempty"`

	// Authorization Bearer token for authentication
	Authorization string `json:"Authorization"`
}

// GetUserOrgsParams defines parameters for GetUserOrgs.
type GetUserOrgsParams struct {
	// Authorization Bearer token for authentication
	Authorization string `json:"Authorization"`
}

// CreateAppJSONRequestBody defines body for CreateApp for application/json ContentType.
type CreateAppJSONRequestBody = CreateAppRequest

// UpdateComponentsJSONRequestBody defines body for UpdateComponents for application/json ContentType.
type UpdateComponentsJSONRequestBody = UpdateComponentsRequest

// CreateDeployCredentialsJSONRequestBody defines body for CreateDeployCredentials for application/json ContentType.
type CreateDeployCredentialsJSONRequestBody = CreateDeployCredentialsRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListApps request
	ListApps(ctx context.Context, params *ListAppsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateAppWithBody request with any body
	CreateAppWithBody(ctx context.Context, params *CreateAppParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateApp(ctx context.Context, params *CreateAppParams, body CreateAppJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteApp request
	DeleteApp(ctx context.Context, appId openapi_types.UUID, params *DeleteAppParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApp request
	GetApp(ctx context.Context, appId openapi_types.UUID, params *GetAppParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListAppComponents request
	ListAppComponents(ctx context.Context, appId openapi_types.UUID, params *ListAppComponentsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateComponentsWithBody request with any body
	UpdateComponentsWithBody(ctx context.Context, appId openapi_types.UUID, params *UpdateComponentsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateComponents(ctx context.Context, appId openapi_types.UUID, params *UpdateComponentsParams, body UpdateComponentsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateDeployCredentialsWithBody request with any body
	CreateDeployCredentialsWithBody(ctx context.Context, appId openapi_types.UUID, params *CreateDeployCredentialsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateDeployCredentials(ctx context.Context, appId openapi_types.UUID, params *CreateDeployCredentialsParams, body CreateDeployCredentialsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAppLogs request
	GetAppLogs(ctx context.Context, appId openapi_types.UUID, params *GetAppLogsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetUserOrgs request
	GetUserOrgs(ctx context.Context, params *GetUserOrgsParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListApps(ctx context.Context, params *ListAppsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListAppsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateAppWithBody(ctx context.Context, params *CreateAppParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateAppRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateApp(ctx context.Context, params *CreateAppParams, body CreateAppJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateAppRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteApp(ctx context.Context, appId openapi_types.UUID, params *DeleteAppParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteAppRequest(c.Server, appId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApp(ctx context.Context, appId openapi_types.UUID, params *GetAppParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAppRequest(c.Server, appId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListAppComponents(ctx context.Context, appId openapi_types.UUID, params *ListAppComponentsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListAppComponentsRequest(c.Server, appId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateComponentsWithBody(ctx context.Context, appId openapi_types.UUID, params *UpdateComponentsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateComponentsRequestWithBody(c.Server, appId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateComponents(ctx context.Context, appId openapi_types.UUID, params *UpdateComponentsParams, body UpdateComponentsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateComponentsRequest(c.Server, appId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateDeployCredentialsWithBody(ctx context.Context, appId openapi_types.UUID, params *CreateDeployCredentialsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateDeployCredentialsRequestWithBody(c.Server, appId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateDeployCredentials(ctx context.Context, appId openapi_types.UUID, params *CreateDeployCredentialsParams, body CreateDeployCredentialsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateDeployCredentialsRequest(c.Server, appId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAppLogs(ctx context.Context, appId openapi_types.UUID, params *GetAppLogsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAppLogsRequest(c.Server, appId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetUserOrgs(ctx context.Context, params *GetUserOrgsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUserOrgsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListAppsRequest generates requests for ListApps
func NewListAppsRequest(server string, params *ListAppsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/apps")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Name != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "name", runtime.ParamLocationQuery, *params.Name); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.IncludeDeleted != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "includeDeleted", runtime.ParamLocationQuery, *params.IncludeDeleted); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "Authorization", runtime.ParamLocationHeader, params.Authorization)
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

// NewCreateAppRequest calls the generic CreateApp builder with application/json body
func NewCreateAppRequest(server string, params *CreateAppParams, body CreateAppJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateAppRequestWithBody(server, params, "application/json", bodyReader)
}

// NewCreateAppRequestWithBody generates requests for CreateApp with any type of body
func NewCreateAppRequestWithBody(server string, params *CreateAppParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/apps")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "Authorization", runtime.ParamLocationHeader, params.Authorization)
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

// NewDeleteAppRequest generates requests for DeleteApp
func NewDeleteAppRequest(server string, appId openapi_types.UUID, params *DeleteAppParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "appId", runtime.ParamLocationPath, appId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/apps/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "Authorization", runtime.ParamLocationHeader, params.Authorization)
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

// NewGetAppRequest generates requests for GetApp
func NewGetAppRequest(server string, appId openapi_types.UUID, params *GetAppParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "appId", runtime.ParamLocationPath, appId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/apps/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "Authorization", runtime.ParamLocationHeader, params.Authorization)
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

// NewListAppComponentsRequest generates requests for ListAppComponents
func NewListAppComponentsRequest(server string, appId openapi_types.UUID, params *ListAppComponentsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "appId", runtime.ParamLocationPath, appId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/apps/%s/components", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "Authorization", runtime.ParamLocationHeader, params.Authorization)
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

// NewUpdateComponentsRequest calls the generic UpdateComponents builder with application/json body
func NewUpdateComponentsRequest(server string, appId openapi_types.UUID, params *UpdateComponentsParams, body UpdateComponentsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateComponentsRequestWithBody(server, appId, params, "application/json", bodyReader)
}

// NewUpdateComponentsRequestWithBody generates requests for UpdateComponents with any type of body
func NewUpdateComponentsRequestWithBody(server string, appId openapi_types.UUID, params *UpdateComponentsParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "appId", runtime.ParamLocationPath, appId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/apps/%s/components", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "Authorization", runtime.ParamLocationHeader, params.Authorization)
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

// NewCreateDeployCredentialsRequest calls the generic CreateDeployCredentials builder with application/json body
func NewCreateDeployCredentialsRequest(server string, appId openapi_types.UUID, params *CreateDeployCredentialsParams, body CreateDeployCredentialsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateDeployCredentialsRequestWithBody(server, appId, params, "application/json", bodyReader)
}

// NewCreateDeployCredentialsRequestWithBody generates requests for CreateDeployCredentials with any type of body
func NewCreateDeployCredentialsRequestWithBody(server string, appId openapi_types.UUID, params *CreateDeployCredentialsParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "appId", runtime.ParamLocationPath, appId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/apps/%s/deploy-credentials", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "Authorization", runtime.ParamLocationHeader, params.Authorization)
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

// NewGetAppLogsRequest generates requests for GetAppLogs
func NewGetAppLogsRequest(server string, appId openapi_types.UUID, params *GetAppLogsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "appId", runtime.ParamLocationPath, appId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/apps/%s/logs", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Since != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "since", runtime.ParamLocationQuery, *params.Since); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Tail != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "tail", runtime.ParamLocationQuery, *params.Tail); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "Authorization", runtime.ParamLocationHeader, params.Authorization)
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

// NewGetUserOrgsRequest generates requests for GetUserOrgs
func NewGetUserOrgsRequest(server string, params *GetUserOrgsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/user/orgs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "Authorization", runtime.ParamLocationHeader, params.Authorization)
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListAppsWithResponse request
	ListAppsWithResponse(ctx context.Context, params *ListAppsParams, reqEditors ...RequestEditorFn) (*ListAppsBody, error)

	// CreateAppWithBodyWithResponse request with any body
	CreateAppWithBodyWithResponse(ctx context.Context, params *CreateAppParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateAppBody, error)

	CreateAppWithResponse(ctx context.Context, params *CreateAppParams, body CreateAppJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateAppBody, error)

	// DeleteAppWithResponse request
	DeleteAppWithResponse(ctx context.Context, appId openapi_types.UUID, params *DeleteAppParams, reqEditors ...RequestEditorFn) (*DeleteAppBody, error)

	// GetAppWithResponse request
	GetAppWithResponse(ctx context.Context, appId openapi_types.UUID, params *GetAppParams, reqEditors ...RequestEditorFn) (*GetAppBody, error)

	// ListAppComponentsWithResponse request
	ListAppComponentsWithResponse(ctx context.Context, appId openapi_types.UUID, params *ListAppComponentsParams, reqEditors ...RequestEditorFn) (*ListAppComponentsBody, error)

	// UpdateComponentsWithBodyWithResponse request with any body
	UpdateComponentsWithBodyWithResponse(ctx context.Context, appId openapi_types.UUID, params *UpdateComponentsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateComponentsBody, error)

	UpdateComponentsWithResponse(ctx context.Context, appId openapi_types.UUID, params *UpdateComponentsParams, body UpdateComponentsJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateComponentsBody, error)

	// CreateDeployCredentialsWithBodyWithResponse request with any body
	CreateDeployCredentialsWithBodyWithResponse(ctx context.Context, appId openapi_types.UUID, params *CreateDeployCredentialsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateDeployCredentialsBody, error)

	CreateDeployCredentialsWithResponse(ctx context.Context, appId openapi_types.UUID, params *CreateDeployCredentialsParams, body CreateDeployCredentialsJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateDeployCredentialsBody, error)

	// GetAppLogsWithResponse request
	GetAppLogsWithResponse(ctx context.Context, appId openapi_types.UUID, params *GetAppLogsParams, reqEditors ...RequestEditorFn) (*GetAppLogsBody, error)

	// GetUserOrgsWithResponse request
	GetUserOrgsWithResponse(ctx context.Context, params *GetUserOrgsParams, reqEditors ...RequestEditorFn) (*GetUserOrgsBody, error)
}

type ListAppsBody struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListAppsResponseBody
	JSON400      *ErrorResponse
	JSON401      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ListAppsBody) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListAppsBody) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateAppBody struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *CreateAppResponseBody
	JSON400      *ErrorResponse
	JSON401      *ErrorResponse
	JSON409      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r CreateAppBody) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateAppBody) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteAppBody struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *DeleteAppResponseBody
	JSON401      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r DeleteAppBody) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteAppBody) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetAppBody struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *App
	JSON401      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetAppBody) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAppBody) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListAppComponentsBody struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListComponentsResponseBody
	JSON401      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ListAppComponentsBody) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListAppComponentsBody) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateComponentsBody struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UpdateComponentsResponseBody
	JSON400      *ErrorResponse
	JSON401      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r UpdateComponentsBody) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateComponentsBody) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateDeployCredentialsBody struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CreateDeployCredentialsResponse
	JSON401      *ErrorResponse
	JSON403      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r CreateDeployCredentialsBody) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateDeployCredentialsBody) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetAppLogsBody struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetAppLogsResponseBody
	JSON400      *ErrorResponse
	JSON401      *ErrorResponse
	JSON403      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetAppLogsBody) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAppLogsBody) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetUserOrgsBody struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetUserOrgsResponseBody
	JSON401      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetUserOrgsBody) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUserOrgsBody) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListAppsWithResponse request returning *ListAppsBody
func (c *ClientWithResponses) ListAppsWithResponse(ctx context.Context, params *ListAppsParams, reqEditors ...RequestEditorFn) (*ListAppsBody, error) {
	rsp, err := c.ListApps(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListAppsBody(rsp)
}

// CreateAppWithBodyWithResponse request with arbitrary body returning *CreateAppBody
func (c *ClientWithResponses) CreateAppWithBodyWithResponse(ctx context.Context, params *CreateAppParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateAppBody, error) {
	rsp, err := c.CreateAppWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateAppBody(rsp)
}

func (c *ClientWithResponses) CreateAppWithResponse(ctx context.Context, params *CreateAppParams, body CreateAppJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateAppBody, error) {
	rsp, err := c.CreateApp(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateAppBody(rsp)
}

// DeleteAppWithResponse request returning *DeleteAppBody
func (c *ClientWithResponses) DeleteAppWithResponse(ctx context.Context, appId openapi_types.UUID, params *DeleteAppParams, reqEditors ...RequestEditorFn) (*DeleteAppBody, error) {
	rsp, err := c.DeleteApp(ctx, appId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteAppBody(rsp)
}

// GetAppWithResponse request returning *GetAppBody
func (c *ClientWithResponses) GetAppWithResponse(ctx context.Context, appId openapi_types.UUID, params *GetAppParams, reqEditors ...RequestEditorFn) (*GetAppBody, error) {
	rsp, err := c.GetApp(ctx, appId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAppBody(rsp)
}

// ListAppComponentsWithResponse request returning *ListAppComponentsBody
func (c *ClientWithResponses) ListAppComponentsWithResponse(ctx context.Context, appId openapi_types.UUID, params *ListAppComponentsParams, reqEditors ...RequestEditorFn) (*ListAppComponentsBody, error) {
	rsp, err := c.ListAppComponents(ctx, appId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListAppComponentsBody(rsp)
}

// UpdateComponentsWithBodyWithResponse request with arbitrary body returning *UpdateComponentsBody
func (c *ClientWithResponses) UpdateComponentsWithBodyWithResponse(ctx context.Context, appId openapi_types.UUID, params *UpdateComponentsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateComponentsBody, error) {
	rsp, err := c.UpdateComponentsWithBody(ctx, appId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateComponentsBody(rsp)
}

func (c *ClientWithResponses) UpdateComponentsWithResponse(ctx context.Context, appId openapi_types.UUID, params *UpdateComponentsParams, body UpdateComponentsJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateComponentsBody, error) {
	rsp, err := c.UpdateComponents(ctx, appId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateComponentsBody(rsp)
}

// CreateDeployCredentialsWithBodyWithResponse request with arbitrary body returning *CreateDeployCredentialsBody
func (c *ClientWithResponses) CreateDeployCredentialsWithBodyWithResponse(ctx context.Context, appId openapi_types.UUID, params *CreateDeployCredentialsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateDeployCredentialsBody, error) {
	rsp, err := c.CreateDeployCredentialsWithBody(ctx, appId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateDeployCredentialsBody(rsp)
}

func (c *ClientWithResponses) CreateDeployCredentialsWithResponse(ctx context.Context, appId openapi_types.UUID, params *CreateDeployCredentialsParams, body CreateDeployCredentialsJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateDeployCredentialsBody, error) {
	rsp, err := c.CreateDeployCredentials(ctx, appId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateDeployCredentialsBody(rsp)
}

// GetAppLogsWithResponse request returning *GetAppLogsBody
func (c *ClientWithResponses) GetAppLogsWithResponse(ctx context.Context, appId openapi_types.UUID, params *GetAppLogsParams, reqEditors ...RequestEditorFn) (*GetAppLogsBody, error) {
	rsp, err := c.GetAppLogs(ctx, appId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAppLogsBody(rsp)
}

// GetUserOrgsWithResponse request returning *GetUserOrgsBody
func (c *ClientWithResponses) GetUserOrgsWithResponse(ctx context.Context, params *GetUserOrgsParams, reqEditors ...RequestEditorFn) (*GetUserOrgsBody, error) {
	rsp, err := c.GetUserOrgs(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUserOrgsBody(rsp)
}

// ParseListAppsBody parses an HTTP response from a ListAppsWithResponse call
func ParseListAppsBody(rsp *http.Response) (*ListAppsBody, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListAppsBody{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListAppsResponseBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCreateAppBody parses an HTTP response from a CreateAppWithResponse call
func ParseCreateAppBody(rsp *http.Response) (*CreateAppBody, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateAppBody{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest CreateAppResponseBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteAppBody parses an HTTP response from a DeleteAppWithResponse call
func ParseDeleteAppBody(rsp *http.Response) (*DeleteAppBody, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteAppBody{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest DeleteAppResponseBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetAppBody parses an HTTP response from a GetAppWithResponse call
func ParseGetAppBody(rsp *http.Response) (*GetAppBody, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAppBody{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest App
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseListAppComponentsBody parses an HTTP response from a ListAppComponentsWithResponse call
func ParseListAppComponentsBody(rsp *http.Response) (*ListAppComponentsBody, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListAppComponentsBody{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListComponentsResponseBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseUpdateComponentsBody parses an HTTP response from a UpdateComponentsWithResponse call
func ParseUpdateComponentsBody(rsp *http.Response) (*UpdateComponentsBody, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateComponentsBody{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UpdateComponentsResponseBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCreateDeployCredentialsBody parses an HTTP response from a CreateDeployCredentialsWithResponse call
func ParseCreateDeployCredentialsBody(rsp *http.Response) (*CreateDeployCredentialsBody, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateDeployCredentialsBody{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CreateDeployCredentialsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetAppLogsBody parses an HTTP response from a GetAppLogsWithResponse call
func ParseGetAppLogsBody(rsp *http.Response) (*GetAppLogsBody, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAppLogsBody{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetAppLogsResponseBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetUserOrgsBody parses an HTTP response from a GetUserOrgsWithResponse call
func ParseGetUserOrgsBody(rsp *http.Response) (*GetUserOrgsBody, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUserOrgsBody{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetUserOrgsResponseBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
