[package]
name = "{{project-name | snake_case}}"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.16.0"
serde_json = "1.0"

[package.metadata.component]
package = "component:{{project-name | kebab_case}}"

[workspace]