spin_manifest_version = 2

[application]
name = "mcp-authorizer"
version = "0.0.1"
authors = ["FTL Contributors"]
description = "Authentication gateway for FTL MCP servers"

[variables]
# Core settings
mcp_gateway_url = { default = "http://mcp-gateway.spin.internal" }
mcp_trace_header = { default = "x-trace-id" }
mcp_provider_type = { default = "jwt" }

# JWT provider settings
mcp_jwt_issuer = { default = "https://test.authkit.app" }
mcp_jwt_audience = { default = "" }
mcp_jwt_jwks_uri = { default = "" }
mcp_jwt_public_key = { default = "" }
mcp_jwt_algorithm = { default = "" }
mcp_jwt_required_scopes = { default = "" }

# OAuth endpoints (optional)
mcp_oauth_authorize_endpoint = { default = "" }
mcp_oauth_token_endpoint = { default = "" }
mcp_oauth_userinfo_endpoint = { default = "" }

# Static provider settings
mcp_static_tokens = { default = "" }

[[trigger.http]]
route = "/..."
component = "mcp-authorizer"

[component.mcp-authorizer]
source = "target/wasm32-wasip1/release/ftl_mcp_authorizer.wasm"
allowed_outbound_hosts = ["http://*.spin.internal", "https://*"]
key_value_stores = ["default"]
[component.mcp-authorizer.build]
command = "cargo build --target wasm32-wasip1 --release --target-dir ./target"
workdir = "."
watch = ["src/**/*.rs", "Cargo.toml"]
[component.mcp-authorizer.variables]
# Core settings
mcp_gateway_url = "{{ mcp_gateway_url }}"
mcp_trace_header = "{{ mcp_trace_header }}"
mcp_provider_type = "{{ mcp_provider_type }}"

# JWT provider settings
mcp_jwt_issuer = "{{ mcp_jwt_issuer }}"
mcp_jwt_audience = "{{ mcp_jwt_audience }}"
mcp_jwt_jwks_uri = "{{ mcp_jwt_jwks_uri }}"
mcp_jwt_public_key = "{{ mcp_jwt_public_key }}"
mcp_jwt_algorithm = "{{ mcp_jwt_algorithm }}"
mcp_jwt_required_scopes = "{{ mcp_jwt_required_scopes }}"

# OAuth endpoints
mcp_oauth_authorize_endpoint = "{{ mcp_oauth_authorize_endpoint }}"
mcp_oauth_token_endpoint = "{{ mcp_oauth_token_endpoint }}"
mcp_oauth_userinfo_endpoint = "{{ mcp_oauth_userinfo_endpoint }}"

# Static provider settings
mcp_static_tokens = "{{ mcp_static_tokens }}"

# Test configuration
[component.mcp-authorizer.tool.spin-test]
source = "tests/target/wasm32-wasip1/release/tests.wasm"
build = "cargo build --target wasm32-wasip1 --release"
workdir = "tests"