spin_manifest_version = 2

[application]
name = "test-app"
version = "0.1.0"

[http_trigger]
route = "/api/..."

[component.tool-json-formatter]
source = { registry = "ghcr.io", package = "fastertools:ftl-tool-json-formatter", version = "0.1.2" }
allowed_outbound_hosts = []
