[package]
name = "weather_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
ftl-sdk = { path = "../../../sdk/rust", features = ["macros"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
schemars = "0.8"
spin-sdk = "3.0"

[lib]
crate-type = ["cdylib"]