[package]
name = "ftl-sdk-rs"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Core library for FTL tools - lightweight MCP server for WebAssembly"
readme = "README.md"
homepage.workspace = true
documentation.workspace = true
keywords = ["wasm", "mcp", "tools", "webassembly", "spin"]
categories = ["wasm", "web-programming", "development-tools"]

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
spin-sdk = "3.1.1"
talc = { version = "4.4", default-features = false, features = ["lock_api"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt", "sync"] }