manifest_version = "1"
id = "ftl-auth-gateway"
description = "MCP Authorizer - JWT authentication gateway for MCP endpoints"
tags = ["mcp", "http", "auth", "jwt", "oauth", "authkit", "gateway"]

[parameters]
jwt-issuer = { type = "string", prompt = "JWT issuer URL (e.g., https://your-tenant.authkit.app)", default = "" }
jwt-audience = { type = "string", prompt = "JWT audience (optional)", default = "" }
jwt-jwks-uri = { type = "string", prompt = "JWKS endpoint URL (optional, auto-detected for AuthKit)", default = "" }

[add_component]
skip_files = ["spin.toml", "README.md", ".gitignore"]
[add_component.snippets]
component = "component.txt"