spin_manifest_version = 2

[application]
name = "mcp-gateway"
version = "0.0.1"
authors = ["FTL Contributors"]
description = "MCP gateway for FTL MCP components"

[variables]
# Components configuration
component_names = { default = "example-component" }
validate_arguments = { default = "true" }

[[trigger.http]]
route = "/..."
component = "mcp-gateway"

[component.mcp-gateway]
source = "target/wasm32-wasip1/release/ftl_mcp_gateway.wasm"
allowed_outbound_hosts = ["http://*.spin.internal"]

[component.mcp-gateway.build]
command = "cargo build --target wasm32-wasip1 --release --target-dir ./target"
workdir = "."
watch = ["src/**/*.rs", "Cargo.toml"]

[component.mcp-gateway.variables]
validate_arguments = "{{ validate_arguments }}"
component_names = "{{ component_names }}"

# Test configuration
[component.mcp-gateway.tool.spin-test]
source = "tests/target/wasm32-wasip1/release/tests.wasm"
build = "cargo build --target wasm32-wasip1 --release"
workdir = "tests"