manifest_version = "1"
id = "ftl-mcp-rust"
description = "Rust FTL MCP tool component"
tags = ["mcp", "http", "rust", "ftl", "tool"]

[add_component]
skip_files = ["spin.toml", "README.md", ".gitignore"]
[add_component.snippets]
component = "component.txt"