application:
    name: physics
    version: 0.1.0
    description: physics - An FTL application
components:
    - id: geo
      source:
        package: bowlofarugula:geo
        registry: ghcr.io
        version: 0.0.1
triggers:
    - type: http
      component: geo
      route: private
