[alias]
i = "install --path cli"
t = "nextest run"
build-wasm = "component build -p ftl-mcp-authorizer -p ftl-mcp-gateway --target wasm32-wasip1"
wasm = "build-wasm"
cov = "llvm-cov nextest --workspace --exclude ftl-cli --exclude ftl-sdk-macros --ignore-filename-regex '(test_helpers|api_client|deps)\\.rs|sdk/rust-macros'"
cov-html = "llvm-cov nextest --workspace --exclude ftl-cli --exclude ftl-sdk-macros --ignore-filename-regex '(test_helpers|api_client|deps)\\.rs|sdk/rust-macros' --open"