# Cargo configuration for FTL workspace
# All Rust code in this project targets WebAssembly

[build]
# Default to WASM target for all builds
target = "wasm32-wasip1"

[target.wasm32-wasip1]
# Optimize for size in release builds
rustflags = ["-C", "link-arg=-s"]  # Strip symbols

[registries]
crates-io = { index = "https://github.com/rust-lang/crates.io-index" }

[net]
# Faster git fetches
git-fetch-with-cli = true

# Useful aliases for common operations
[alias]
# Build aliases
wasm = "build --target wasm32-wasip1"
wasm-release = "build --target wasm32-wasip1 --release"

# Component-specific builds
build-gateway = "build -p mcp-gateway --target wasm32-wasip1 --release"
build-authorizer = "build -p mcp-authorizer --target wasm32-wasip1 --release"
build-components = "build --workspace --target wasm32-wasip1 --release"

# Testing (note: most tests need to run on host, not WASM)
test-host = "test --target x86_64-unknown-linux-gnu"
test-host-mac = "test --target aarch64-apple-darwin"

# Checking
check-all = "check --workspace --all-targets"
clippy-all = "clippy --workspace --all-targets -- -D warnings"