# Example FTL Registry Configuration
# This file would typically be located at ~/.ftl/registries.toml

version = "1"
default_registry = "ghcr"  # Which registry to use when no --registry flag is provided

# GitHub Container Registry (default for FTL tools)
[[registries]]
name = "ghcr"
type = "ghcr"
enabled = true
priority = 1  # Highest priority for searches
[registries.config]
organization = "fastertools"

# Docker Hub
[[registries]]
name = "docker"
type = "docker" 
enabled = true
priority = 2

# AWS Elastic Container Registry
[[registries]]
name = "ecr"
type = "ecr"
enabled = false  # Disabled by default, enable when AWS credentials are configured
priority = 3
[registries.config]
# These can be overridden by AWS_ACCOUNT_ID and AWS_REGION env vars
account_id = "123456789012"
region = "us-east-1"

# Example: Private GitLab Registry
[[registries]]
name = "gitlab"
type = "custom"
enabled = false
priority = 4
[registries.config]
url_pattern = "registry.gitlab.com/myorg/ftl-tools/{image_name}:latest"
auth_type = "bearer"  # Will use token from keyring

# Example: Self-hosted Registry
[[registries]]
name = "internal"
type = "custom"
enabled = false
priority = 5
[registries.config]
url_pattern = "registry.internal.company.com/ftl/{image_name}:latest"
auth_type = "basic"  # Will use username/password from keyring