[project]
name = "authkit-example"
version = "0.1.0"
description = "FTL MCP server for hosting MCP tools"
authors = []

[auth]
enabled = true

[mcp]
gateway = "ghcr.io/fastertools/mcp-gateway:0.0.10"
authorizer = "ghcr.io/fastertools/mcp-authorizer:0.0.10"
validate_arguments = true

[auth.authkit]
issuer = "https://divine-lion-50-staging.authkit.app"
# audience = "mcp-api"  # optional
# required_scopes = "mcp:read,mcp:write"  # optional

# Uncomment for development with static tokens:
# [auth]
# enabled = true
# 
# [auth.static_token]
# tokens = "dev-token:dev-client:dev-user:read,write"
# required_scopes = "read"

[tools.example-tool-component]
path = "example-tool-component"
wasm = "example-tool-component/target/wasm32-wasip1/release/example_tool_component.wasm"
allowed_outbound_hosts = []

[tools.example-tool-component.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = [
    "src/**/*.rs",
    "Cargo.toml",
]
