spin_manifest_version = 2

[application]
name = "test-project"
version = "0.1.0"

[component.tool-json-formatter]
source = { registry = "ghcr.io", package = "fastertools:ftl-tool-json-formatter", version = "1.0.0" }

[component.tool-yaml-validator]
source = { registry = "ghcr.io", package = "fastertools:ftl-tool-yaml-validator", version = "1.5.0" }

[[trigger.http]]
route = "/..."
component = "tool-json-formatter"
