application:
    name: physics
    version: 0.1.0
    description: physics - An FTL application
components:
    - id: geo
      source:
        package: bowlofarugula:geo
        registry: ghcr.io
        version: 0.0.1
    - id: local-comp
      source: ./my-component.wasm
    - id: url-comp
      source:
        url: https://example.com/component.wasm
        digest: sha256:abc123
triggers:
    - type: http
      component: geo
      route: private
    - type: http
      component: local-comp
      route: private
    - type: http
      component: url-comp
      route: private