spin_manifest_version = 2

[application]
description = "physics - An FTL application"
name = "physics"
version = "0.1.0"

[component.geo]
source = { registry = "ghcr.io", package = "bowlofarugula:geo", version = "0.0.1" }

[component.local-comp]
source = "./my-component.wasm"

[component.url-comp]
source = { url = "https://example.com/component.wasm", digest = "sha256:abc123" }

[component.ftl-mcp-gateway]
source = "./.ftl/wasm/mcp-gateway-latest.wasm"
allowed_outbound_hosts = ["http://*.spin.internal"]

[component.ftl-mcp-gateway.variables]
component_names = "geo,local-comp,url-comp"

[[trigger.http]]
route = "/mcp"
component = "ftl-mcp-gateway"

[[trigger.http]]
route = { private = true }
component = "geo"

[[trigger.http]]
route = { private = true }
component = "local-comp"

[[trigger.http]]
route = { private = true }
component = "url-comp"
