# Nextest configuration for ftl-cli

[profile.default]
# Run tests using as many threads as available
test-threads = "num-cpus"

# Terminate test run on first failure (fail-fast behavior)
fail-fast = true

# Show output for failed tests immediately
failure-output = "immediate"

# Don't show output for successful tests
success-output = "never"

# Show test status at these levels
status-level = "fail"
final-status-level = "fail"

# Tests are marked slow after 30 seconds, terminate after 60 seconds
slow-timeout = { period = "30s", terminate-after = 2 }

[profile.ci]
# CI-specific configuration
# Don't fail fast in CI - run all tests to see all failures
fail-fast = false

# Show more detailed output in CI
status-level = "retry"
final-status-level = "slow"

# Retry flaky tests once in CI
retries = 1

# Be more generous with timeouts in CI
slow-timeout = { period = "60s", terminate-after = 3 }

# Show which tests were retried
failure-output = "final"
success-output = "never"