// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "fmt"

// ControlCenter combines status monitoring and control functionality into a unified panel
func ControlCenter(project Project, processStatus ProcessStatus, serverStatus ServerStatus, commandHistory []CommandOutput) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div><h2 class=\"text-lg font-semibold mb-4 text-white\">Control Center</h2><div class=\"space-y-4\"><!-- Process Status Section --><div><h3 class=\"text-sm font-medium mb-3\" style=\"color: #a0a0a0;\">Process Status</h3><div id=\"ftl-status\" hx-post=\"/htmx/status/poll\" hx-trigger=\"load, every 3s\" hx-swap=\"innerHTML\" hx-vals=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf(`{"project_path": "%s"}`, project.Path))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/control_center.templ`, Line: 18, Col: 67}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" class=\"space-y-2\"><!-- Process status rows - will be replaced by HTMX --><div class=\"flex items-center justify-between p-2 rounded\" style=\"background-color: #333333;\"><div class=\"flex items-center space-x-3\"><span class=\"text-sm font-medium text-white\">FTL Process</span><div class=\"w-2 h-2 bg-gray-500 rounded-full\"></div><span class=\"text-xs font-mono\" style=\"color: #666666;\">Stopped</span></div></div><div class=\"flex items-center justify-between p-2 rounded\" style=\"background-color: #333333;\"><div class=\"flex items-center space-x-3\"><span class=\"text-sm font-medium text-white\">Watch Mode</span><div class=\"w-2 h-2 bg-gray-500 rounded-full\"></div><span class=\"text-xs font-mono\" style=\"color: #666666;\">Inactive</span></div></div></div></div><!-- Control Buttons Section --><div class=\"border-t pt-4\" style=\"border-color: #3a3a3a;\"><h3 class=\"text-sm font-medium mb-3\" style=\"color: #a0a0a0;\">Operations</h3><div class=\"p-4 rounded-lg\" style=\"background-color: #333333;\"><div class=\"grid grid-cols-3 gap-3\"><!-- Build Button --><form hx-post=\"/mcp\" hx-target=\"#ftl-output\" hx-swap=\"beforeend\" hx-on::before-request=\"document.getElementById('ftl-output').insertAdjacentHTML('beforeend', '<div class=\\'text-blue-400\\'>[' + new Date().toTimeString().slice(0,8) + '] Sending build command...</div>')\"><input type=\"hidden\" name=\"action\" value=\"build\"> <input type=\"hidden\" name=\"project-path\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(project.Path)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/control_center.templ`, Line: 49, Col: 68}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\"> <button type=\"submit\" class=\"w-full text-white text-sm py-2.5 px-4 rounded-md transition-all duration-200 font-medium\" style=\"background-color: #4a4a4a; border: 1px solid #5a5a5a;\" onmouseover=\"this.style.backgroundColor='#5a5a5a'; this.style.borderColor='#6a6a6a'; this.style.transform='translateY(-1px)'\" onmouseout=\"this.style.backgroundColor='#4a4a4a'; this.style.borderColor='#5a5a5a'; this.style.transform='translateY(0)'\">Build</button></form><!-- Up (Regular Mode) Button --><form hx-post=\"/mcp\" hx-target=\"#ftl-output\" hx-swap=\"beforeend\" hx-on::before-request=\"document.getElementById('ftl-output').insertAdjacentHTML('beforeend', '<div class=\\'text-blue-400\\'>[' + new Date().toTimeString().slice(0,8) + '] Starting FTL server...</div>')\"><input type=\"hidden\" name=\"action\" value=\"up\"> <input type=\"hidden\" name=\"project-path\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(project.Path)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/control_center.templ`, Line: 67, Col: 68}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\"> <input type=\"hidden\" name=\"mode\" value=\"regular\"> <button type=\"submit\" class=\"w-full text-white text-sm py-2.5 px-4 rounded-md transition-all duration-200 font-medium\" style=\"background-color: #4a4a4a; border: 1px solid #5a5a5a;\" onmouseover=\"this.style.backgroundColor='#5a5a5a'; this.style.borderColor='#6a6a6a'; this.style.transform='translateY(-1px)'\" onmouseout=\"this.style.backgroundColor='#4a4a4a'; this.style.borderColor='#5a5a5a'; this.style.transform='translateY(0)'\">Up</button></form><!-- Up (Watch Mode) Button --><form hx-post=\"/mcp\" hx-target=\"#ftl-output\" hx-swap=\"beforeend\" hx-on::before-request=\"document.getElementById('ftl-output').insertAdjacentHTML('beforeend', '<div class=\\'text-blue-400\\'>[' + new Date().toTimeString().slice(0,8) + '] Starting FTL in watch mode...</div>')\"><input type=\"hidden\" name=\"action\" value=\"up\"> <input type=\"hidden\" name=\"project-path\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(project.Path)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/control_center.templ`, Line: 86, Col: 68}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\"> <input type=\"hidden\" name=\"mode\" value=\"watch\"> <button type=\"submit\" class=\"w-full text-white text-sm py-2.5 px-4 rounded-md transition-all duration-200 font-medium\" style=\"background-color: #4a4a4a; border: 1px solid #5a5a5a;\" onmouseover=\"this.style.backgroundColor='#5a5a5a'; this.style.borderColor='#6a6a6a'; this.style.transform='translateY(-1px)'\" onmouseout=\"this.style.backgroundColor='#4a4a4a'; this.style.borderColor='#5a5a5a'; this.style.transform='translateY(0)'\">Watch</button></form></div></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
