spin_manifest_version = 2

[application]
name = "{{project-name | kebab_case}}"
version = "0.1.0"
authors = ["{{authors}}"]
description = "{{project-description}}"

[[trigger.http]]
route = "/mcp"
component = "mcp-gateway"

[component.mcp-gateway]
# Using the published gateway component
source = { registry = "{{registry}}", package = "{{gateway-package}}", version = "{{gateway-version}}" }

[component.mcp-gateway.dependencies]
# Link to the local handler component
"component:mcp/handler@0.1.0" = { path = "./handler/target/wasm32-wasip1/release/{{project-name | snake_case}}.wasm" }