// Code generated by ui/generate.go. DO NOT EDIT.

package ui

// Color constants
var Colors = struct {
	Primary   struct{ BG, Text string }
	Secondary struct{ BG, Text string }
	Accents   map[string]string
	Status    map[string]string
}{
	Primary:   struct{ BG, Text string }{BG: "#1a1a1a", Text: "#ffffff"},
	Secondary: struct{ BG, Text string }{BG: "#2a2a2a", Text: "#a0a0a0"},
	Accents: map[string]string{
		"green":  "#22c55e",
		"blue":   "#3b82f6",
		"orange": "#f97316",
		"red":    "#ef4444",
		"yellow": "#f59e0b",
		"gray":   "#666666",
	},
	Status: map[string]string{
		"running":  "#22c55e",
		"stopped":  "#666666",
		"error":    "#ef4444",
		"warning":  "#f97316",
		"inactive": "#666666",
		"building": "#3b82f6",
		"starting": "#f59e0b",
	},
}

// CSS class mappings
var CSSClasses = struct {
	Text       map[string]string
	StatusDots map[string]string
	Buttons    map[string]string
	Panels     map[string]string
}{
	Text: map[string]string{
		"success": "text-green-400",
		"error":   "text-red-400",
		"info":    "text-blue-400",
		"warning": "text-orange-400",
		"muted":   "text-gray-400",
		"primary": "text-white",
	},
	StatusDots: map[string]string{
		"running":  "bg-green-500",
		"stopped":  "bg-gray-500",
		"error":    "bg-red-500",
		"warning":  "bg-orange-500",
		"building": "bg-blue-500",
		"inactive": "bg-gray-500",
	},
	Buttons: map[string]string{
		"primary":   "bg-blue-600 hover:bg-blue-700 text-white",
		"secondary": "bg-gray-600 hover:bg-gray-700 text-white",
		"danger":    "bg-red-600 hover:bg-red-700 text-white",
		"success":   "bg-green-600 hover:bg-green-700 text-white",
		"ghost":     "hover:bg-gray-700 text-gray-300",
	},
	Panels: map[string]string{
		"main":     "bg-primary rounded-lg shadow-lg",
		"sidebar":  "bg-secondary rounded-lg",
		"activity": "bg-primary rounded-lg",
		"control":  "bg-secondary rounded-lg p-4",
	},
}
