spin_manifest_version = 2

[application]
name = "my-scientific-platform"
version = "0.1.0"
description = "Geo and fluid dynamics computation platform"

[component.fluid]
source = { registry = "ghcr.io", package = "bowlofarugula/fluid", version = "0.0.1" }

[component.fluid.variables]
PRECISION = "double"

[component.ftl-mcp-gateway]
source = { registry = "ghcr.io", package = "fastertools:mcp-gateway", version = "0.0.13-alpha.0" }
allowed_outbound_hosts = ["http://*.spin.internal"]

[component.ftl-mcp-gateway.variables]
component_names = "fluid,geo"

[component.geo]
source = { registry = "ghcr.io", package = "bowlofarugula/geo", version = "0.0.1" }

[component.geo.variables]
LOG_LEVEL = "info"

[[trigger.http]]
route = "/..."
component = "ftl-mcp-gateway"

[[trigger.http]]
route = { private = true }
component = "geo"

[[trigger.http]]
route = { private = true }
component = "fluid"

