// Code generated by go run generate.go; DO NOT EDIT.

package constants

// ValidLanguages lists all supported FTL project languages
var ValidLanguages = []string{
	"rust",
	"typescript",
	"python",
	"go",
}

// ValidFormats lists all supported configuration file formats
var ValidFormats = []string{
	"yaml",
	"json",
	"cue",
	"go",
}

// OrderedKeys defines the column order for CLI table output
var OrderedKeys = []string{
	"Name",
	"ID",
	"Status",
	"URL",
	"Error",
	"Access",
	"OrgID",
	"Created",
	"Updated",
}

// MCPCoreTools lists the core MCP tools provided by FTL
var MCPCoreTools = []string{
	"ftl-init",
	"ftl-build",
	"ftl-up",
	"ftl-status",
	"ftl-logs",
}

// WatchPatterns maps languages to their file watch patterns
var WatchPatterns = map[string][]string{
	"go": {
		"**/*.go",
		"go.mod",
	},
	"python": {
		"**/*.py",
	},
	"rust": {
		"src/**/*.rs",
		"Cargo.toml",
	},
	"typescript": {
		"src/**/*.js",
		"package.json",
	},
}

// ConfigPriorities defines config file search priorities by context
var ConfigPriorities = map[string][]string{
	"build": {
		"ftl.yaml",
		"ftl.json",
		"app.cue",
		"main.go",
	},
	"default": {
		"ftl.yaml",
		"ftl.yml",
		"ftl.json",
		"app.cue",
	},
	"synth": {
		"ftl.yaml",
		"ftl.yml",
		"ftl.json",
		"main.go",
		"platform.go",
		"ftl.cue",
		"app.cue",
	},
}
