manifest_version = "1"
id = "mcp-server"
description = "Complete MCP server with handler and gateway"
tags = ["mcp", "http", "rust"]

[parameters]
project-description = { type = "string", prompt = "Description", default = "An MCP server with custom tools" }
route = { type = "string", prompt = "HTTP route", default = "/mcp" }
gateway-version = { type = "string", prompt = "MCP gateway version", default = "0.1.0" }
registry = { type = "string", prompt = "Registry for gateway component (e.g. ghcr.io)", default = "ghcr.io" }
gateway-package = { type = "string", prompt = "Gateway package name", default = "bowlofarugula:mcp-gateway" }

[add_component]
skip_files = ["spin.toml", "README.md", "Makefile", ".gitignore"]
[add_component.snippets]
component = "component.txt"