name: Check Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-readme:
    name: Check README files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check for broken links in main README
        run: |
          # Basic check for broken markdown links
          grep -oE '\[([^\]]+)\]\(([^)]+)\)' README.md | grep -v http | while read -r link; do
            path=$(echo "$link" | sed -E 's/\[[^\]]+\]\(([^)]+)\)/\1/')
            if [[ "$path" == "#"* ]]; then
              continue  # Skip anchor links
            fi
            if [[ ! -f "$path" ]]; then
              echo "Error: Broken link in README.md: $path"
              exit 1
            fi
          done
      
      - name: Check CLI help matches README
        run: |
          cd packages/ftl-cli
          cargo build --release
          
          # Generate help text
          ./target/release/ftl --help > /tmp/ftl-help.txt
          
          # Check if key commands are documented
          for cmd in init add build up test publish deploy registry setup; do
            if ! grep -q "^    $cmd" /tmp/ftl-help.txt; then
              echo "Error: Command '$cmd' not found in ftl --help"
              exit 1
            fi
          done
      
      - name: Check template READMEs exist
        run: |
          for lang in rust typescript javascript; do
            if [[ ! -f "packages/ftl-cli/src/templates/$lang/content/README.md" ]]; then
              echo "Error: Missing README.md for $lang template"
              exit 1
            fi
          done