name: Check SDK Versions

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/ftl-sdk-*/**'
      - 'packages/ftl-cli/src/templates/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'packages/ftl-sdk-*/**'
      - 'packages/ftl-cli/src/templates/**'

jobs:
  check-versions:
    name: Check SDK Version Consistency
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Check Rust SDK version in template
        run: |
          SDK_VERSION=$(grep '^version' packages/ftl-sdk-rust/Cargo.toml | cut -d'"' -f2)
          TEMPLATE_VERSION=$(grep 'ftl-sdk' packages/ftl-cli/src/templates/rust/content/handler/Cargo.toml | cut -d'"' -f2)
          
          echo "Rust SDK version: $SDK_VERSION"
          echo "Rust template SDK version: $TEMPLATE_VERSION"
          
          if [ "$SDK_VERSION" != "$TEMPLATE_VERSION" ]; then
            echo "Error: Rust SDK version ($SDK_VERSION) does not match template version ($TEMPLATE_VERSION)"
            echo "Please update packages/ftl-cli/src/templates/rust/content/handler/Cargo.toml"
            exit 1
          fi
      
      - name: Check TypeScript SDK version in TypeScript template
        run: |
          SDK_VERSION=$(node -p "require('./packages/ftl-sdk-typescript/package.json').version")
          TEMPLATE_VERSION=$(node -p "require('./packages/ftl-cli/src/templates/typescript/content/handler/package.json').dependencies['@fastertools/ftl-sdk']")
          
          # Remove any ^ or ~ prefix from template version
          TEMPLATE_VERSION=${TEMPLATE_VERSION#^}
          TEMPLATE_VERSION=${TEMPLATE_VERSION#~}
          
          echo "TypeScript SDK version: $SDK_VERSION"
          echo "TypeScript template SDK version: $TEMPLATE_VERSION"
          
          if [ "$SDK_VERSION" != "$TEMPLATE_VERSION" ]; then
            echo "Error: TypeScript SDK version ($SDK_VERSION) does not match template version ($TEMPLATE_VERSION)"
            echo "Please update packages/ftl-cli/src/templates/typescript/content/handler/package.json"
            exit 1
          fi
      
      - name: Check TypeScript SDK version in JavaScript template
        run: |
          SDK_VERSION=$(node -p "require('./packages/ftl-sdk-typescript/package.json').version")
          TEMPLATE_VERSION=$(node -p "require('./packages/ftl-cli/src/templates/javascript/content/handler/package.json').dependencies['@fastertools/ftl-sdk']")
          
          # Remove any ^ or ~ prefix from template version
          TEMPLATE_VERSION=${TEMPLATE_VERSION#^}
          TEMPLATE_VERSION=${TEMPLATE_VERSION#~}
          
          echo "TypeScript SDK version: $SDK_VERSION"
          echo "JavaScript template SDK version: $TEMPLATE_VERSION"
          
          if [ "$SDK_VERSION" != "$TEMPLATE_VERSION" ]; then
            echo "Error: TypeScript SDK version ($SDK_VERSION) does not match JavaScript template version ($TEMPLATE_VERSION)"
            echo "Please update packages/ftl-cli/src/templates/javascript/content/handler/package.json"
            exit 1
          fi