name: Check Version Consistency

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-versions:
    name: Check Version Consistency
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check Cargo.toml versions match
        run: |
          # Get workspace version
          WORKSPACE_VERSION=$(grep '^version' Cargo.toml | head -1 | cut -d'"' -f2)
          echo "Workspace version: $WORKSPACE_VERSION"
          
          # Check ftl-cli version
          CLI_VERSION=$(grep '^version' packages/ftl-cli/Cargo.toml | head -1 | cut -d'"' -f2)
          echo "CLI version: $CLI_VERSION"
          
          if [ "$WORKSPACE_VERSION" != "$CLI_VERSION" ]; then
            echo "Error: Workspace version ($WORKSPACE_VERSION) does not match CLI version ($CLI_VERSION)"
            exit 1
          fi
      
      - name: Check SDK dependency versions in templates
        run: |
          # Check Rust SDK version
          RUST_SDK_VERSION=$(grep '^version' packages/ftl-sdk-rust/Cargo.toml | cut -d'"' -f2)
          RUST_TEMPLATE_VERSION=$(grep 'ftl-sdk' packages/ftl-cli/src/templates/rust/content/handler/Cargo.toml | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
          
          echo "Rust SDK version: $RUST_SDK_VERSION"
          echo "Rust template SDK version: $RUST_TEMPLATE_VERSION"
          
          if [ "$RUST_SDK_VERSION" != "$RUST_TEMPLATE_VERSION" ]; then
            echo "Warning: Rust SDK version mismatch"
          fi
          
          # Check TypeScript SDK version
          TS_SDK_VERSION=$(node -p "require('./packages/ftl-sdk-typescript/package.json').version")
          TS_TEMPLATE_VERSION=$(node -p "require('./packages/ftl-cli/src/templates/typescript/content/handler/package.json').dependencies['@fastertools/ftl-sdk']" | sed 's/[\^~]//')
          JS_TEMPLATE_VERSION=$(node -p "require('./packages/ftl-cli/src/templates/javascript/content/handler/package.json').dependencies['@fastertools/ftl-sdk']" | sed 's/[\^~]//')
          
          echo "TypeScript SDK version: $TS_SDK_VERSION"
          echo "TypeScript template SDK version: $TS_TEMPLATE_VERSION"
          echo "JavaScript template SDK version: $JS_TEMPLATE_VERSION"
          
          if [ "$TS_SDK_VERSION" != "$TS_TEMPLATE_VERSION" ]; then
            echo "Warning: TypeScript SDK version mismatch in TypeScript template"
          fi
          
          if [ "$TS_SDK_VERSION" != "$JS_TEMPLATE_VERSION" ]; then
            echo "Warning: TypeScript SDK version mismatch in JavaScript template"
          fi