name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build-binaries:
    name: Build Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary: ftl
            asset_name: ftl-x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
            binary: ftl
            asset_name: ftl-x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
            binary: ftl
            asset_name: ftl-aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary: ftl.exe
            asset_name: ftl-x86_64-pc-windows-msvc.exe

    steps:
      - uses: actions/checkout@v4
      
      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        shell: bash
      
      - name: Validate version matches Cargo.toml
        run: |
          # Since ftl-cli uses workspace version, check the root Cargo.toml
          CARGO_VERSION=$(grep '^version' Cargo.toml | head -1 | cut -d'"' -f2)
          if [ "$CARGO_VERSION" != "${{ steps.version.outputs.VERSION }}" ]; then
            echo "Error: Tag version (${{ steps.version.outputs.VERSION }}) does not match workspace version ($CARGO_VERSION)"
            exit 1
          fi
        shell: bash
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        run: |
          cargo build --release --target ${{ matrix.target }} --bin ftl
        shell: bash
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: ./target/${{ matrix.target }}/release/${{ matrix.binary }}
          if-no-files-found: error
  
  create-release:
    name: Create Release
    needs: build-binaries
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.url }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: binaries
      
      - name: Prepare release assets
        run: |
          mkdir -p release-assets
          for dir in binaries/*/; do
            asset_name=$(basename "$dir")
            if [ -f "${dir}ftl" ]; then
              cp "${dir}ftl" "release-assets/${asset_name}"
            elif [ -f "${dir}ftl.exe" ]; then
              cp "${dir}ftl.exe" "release-assets/${asset_name}"
            fi
          done
          ls -la release-assets/
        shell: bash
      
      - name: Create Release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          files: release-assets/*

  publish-crates:
    name: Publish to crates.io
    needs: create-release
    runs-on: ubuntu-latest
    if: needs.create-release.outputs.release_created
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Publish ftl-sdk
        run: |
          cd packages/ftl-sdk-rust
          # Check if this version is already published
          if cargo search ftl-sdk --limit 1 | grep -q "^ftl-sdk = \"$(grep '^version' Cargo.toml | cut -d'"' -f2)\""; then
            echo "ftl-sdk version already published, skipping"
          else
            cargo publish
          fi
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      
      - name: Wait for ftl-sdk to be available
        run: sleep 30
      
      - name: Publish ftl-cli
        run: |
          cd packages/ftl-cli
          # Check if this version is already published
          # Since ftl-cli uses workspace version, get version from root
          WORKSPACE_VERSION=$(grep '^version' ../../Cargo.toml | head -1 | cut -d'"' -f2)
          if cargo search ftl-cli --limit 1 | grep -q "^ftl-cli = \"$WORKSPACE_VERSION\""; then
            echo "ftl-cli version already published, skipping"
          else
            cargo publish
          fi
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  publish-npm:
    name: Publish to npm
    needs: create-release
    runs-on: ubuntu-latest
    if: needs.create-release.outputs.release_created
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Validate version matches
        run: |
          PACKAGE_VERSION=$(node -p "require('./packages/ftl-sdk-typescript/package.json').version")
          TAG_VERSION="${GITHUB_REF#refs/tags/v}"
          if [ "$PACKAGE_VERSION" != "$TAG_VERSION" ]; then
            echo "Error: Tag version ($TAG_VERSION) does not match package.json version ($PACKAGE_VERSION)"
            exit 1
          fi
      
      - name: Install dependencies
        run: |
          cd packages/ftl-sdk-typescript
          npm ci
      
      - name: Build TypeScript SDK
        run: |
          cd packages/ftl-sdk-typescript
          npm run build
      
      - name: Run tests
        run: |
          cd packages/ftl-sdk-typescript
          npm test
      
      - name: Publish to npm
        run: |
          cd packages/ftl-sdk-typescript
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}