name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  build-binaries:
    name: Build Binaries
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary: ftl
            asset_name: ftl-linux-amd64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            binary: ftl
            asset_name: ftl-linux-arm64
          - os: macos-latest
            target: x86_64-apple-darwin
            binary: ftl
            asset_name: ftl-darwin-amd64
          - os: macos-latest
            target: aarch64-apple-darwin
            binary: ftl
            asset_name: ftl-darwin-arm64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary: ftl.exe
            asset_name: ftl-windows-amd64.exe
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      
      - name: Install cross (Linux ARM64)
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: cargo install cross
      
      - name: Build
        run: |
          if [[ "${{ matrix.target }}" == "aarch64-unknown-linux-gnu" ]]; then
            cross build --release --target ${{ matrix.target }} --bin ftl
          else
            cargo build --release --target ${{ matrix.target }} --bin ftl
          fi
        shell: bash
      
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./target/${{ matrix.target }}/release/${{ matrix.binary }}
          asset_name: ${{ matrix.asset_name }}
          asset_content_type: application/octet-stream

  publish-crates:
    name: Publish to crates.io
    needs: build-binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Publish ftl-core
        run: |
          cd ftl-core
          cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
        continue-on-error: true
      
      - name: Wait for crates.io to index
        run: sleep 30
      
      - name: Publish ftl-runtime
        run: |
          cd ftl-runtime
          cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
        continue-on-error: true
      
      - name: Wait for crates.io to index
        run: sleep 30
      
      - name: Publish ftl CLI
        run: |
          cd ftl-cli
          cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
        continue-on-error: true